# Generated by Django 2.1.4 on 2019-01-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/None/default.jpg', upload_to='profile_pics/'),
        ),
    ]
